/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 *
 * @author User
 */
public class CalificarReinaForm extends javax.swing.JFrame {
    
    
    
    private String dato;
    private String dato1;
    private String dato2;
    private String dato3;
    private String dato4;
    private String dato5;
    private int inteligencia1;
    private int inteligencia2;
    private int inteligencia3;
    private int belleza1;
    private int belleza2;
    private int belleza3;
    

    /**
     * Creates new form Calificar
     */
    public CalificarReinaForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jButtonReina1 = new javax.swing.JButton();
        jLabelCalificarReinas = new javax.swing.JLabel();
        jLabelReina1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonReina2 = new javax.swing.JButton();
        jLabelReina3 = new javax.swing.JLabel();
        jButtonReina3 = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonReina1.setText("Select");
        jButtonReina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReina1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 180, 90, 30));

        jLabelCalificarReinas.setBackground(new java.awt.Color(0, 0, 204));
        jLabelCalificarReinas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelCalificarReinas.setForeground(new java.awt.Color(51, 51, 0));
        jLabelCalificarReinas.setText("Calificar Reinas");
        getContentPane().add(jLabelCalificarReinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jLabelReina1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelReina1.setForeground(new java.awt.Color(51, 51, 0));
        jLabelReina1.setText("Reina 1 ");
        getContentPane().add(jLabelReina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("Reina 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jButtonReina2.setText("Select");
        jButtonReina2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReina2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReina2, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 310, 90, 30));

        jLabelReina3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelReina3.setForeground(new java.awt.Color(51, 51, 0));
        jLabelReina3.setText("Reina 3");
        getContentPane().add(jLabelReina3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jButtonReina3.setText("Select");
        jButtonReina3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReina3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReina3, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 430, 90, 30));

        jButtonRegresar.setBackground(new java.awt.Color(102, 102, 0));
        jButtonRegresar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, -1, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/R11.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 0, 780, 1070));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReina1ActionPerformed
        // TODO add your handling code here:
    // TODO add your handling code here:
        // Cerrar la ventana actual
        dispose();
        
        // Crear una instancia de la nueva ventana
        CalificarReinaForm1 calificarReinaForm = new CalificarReinaForm1();
        
        // Hacer visible el JFrame
        calificarReinaForm.setVisible(true);
    }//GEN-LAST:event_jButtonReina1ActionPerformed

    private void jButtonReina2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReina2ActionPerformed
        // TODO add your handling code here:
    // TODO add your handling code here:
        // Cerrar la ventana actual
        dispose();
        
        // Crear una instancia de la nueva ventana
        CalificarReinaForm2 calificarReinaForm = new CalificarReinaForm2();
        
        // Hacer visible el JFrame
        calificarReinaForm.setVisible(true);
    }//GEN-LAST:event_jButtonReina2ActionPerformed

    private void jButtonReina3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReina3ActionPerformed
        // TODO add your handling code here:
    /// TODO add your handling code here:
        // Cerrar la ventana actual
        dispose();
        
        // Crear una instancia de la nueva ventana
        CalificarReinaForm3 calificarReinaForm = new CalificarReinaForm3();
        
        // Hacer visible el JFrame
        calificarReinaForm.setVisible(true);
    }//GEN-LAST:event_jButtonReina3ActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
     // TODO add your handling code here:
        // Cerrar la ventana actual
        dispose();
        
        // Crear una instancia de la ventana anterior (MenuNivel2)
        MenuNivel2 menu = new MenuNivel2();
        
        // Hacer visible el JFrame
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalificarReinaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalificarReinaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalificarReinaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalificarReinaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalificarReinaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonReina1;
    private javax.swing.JButton jButtonReina2;
    private javax.swing.JButton jButtonReina3;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCalificarReinas;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelReina1;
    private javax.swing.JLabel jLabelReina3;
    // End of variables declaration//GEN-END:variables

       public void setDato(String dato) {
        this.dato = dato;
    }

    public void setDato1(String dato1) {
        this.dato1 = dato1;
    }
    public void setDato2(String dato2) {
        this.dato2 = dato2;
    }

    public void setDato3(String dato3) {
        this.dato3 = dato3;
    }
    public void setDato4(String dato4) {
        this.dato4 = dato4;
    }

    public void setDato5(String dato5) {
        this.dato5 = dato5;
    }


}
