/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class CalificarReinaForm2 extends javax.swing.JFrame {
    
    private int inteligencia2;
    private int belleza2;
    private static String nombreUsuario;
    
    /**
     * Creates new form CalificarReinaForm2
     */
    public CalificarReinaForm2() {
        initComponents();
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        CalificarReinaForm2.nombreUsuario = nombreUsuario; // Establecer el valor en la variable estática
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelInteligencia = new javax.swing.JLabel();
        jTextFieldInteligencia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBelleza = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabelFondos = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(51, 51, 0));
        jLabelTitulo.setText("Calificar Reina 2 ");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, 50));

        jLabelInteligencia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelInteligencia.setForeground(new java.awt.Color(51, 51, 0));
        jLabelInteligencia.setText("Ingrese la puntuación de Inteligencia (entre 0 y 10):");
        getContentPane().add(jLabelInteligencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jTextFieldInteligencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInteligenciaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldInteligencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 190, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 0));
        jLabel2.setText("Ingrese la puntuación de Belleza (entre 0 y 10):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jTextFieldBelleza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBellezaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBelleza, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 180, 40));

        jButtonGuardar.setBackground(new java.awt.Color(102, 102, 0));
        jButtonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar Datos");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 220, 50));

        jButtonRegresar.setBackground(new java.awt.Color(102, 102, 0));
        jButtonRegresar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 630, -1, -1));

        jLabelFondos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/R.jpg"))); // NOI18N
        getContentPane().add(jLabelFondos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-790, -40, 1430, 1070));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
    try {
            // Obtener los datos de inteligencia y belleza ingresados en los campos de texto
            inteligencia2 = Integer.parseInt(jTextFieldInteligencia.getText());
            belleza2 = Integer.parseInt(jTextFieldBelleza.getText());

            // Obtener el nombre de usuario
           

            // Guardar los datos en la base de datos
            try {
                // Establecer la conexión con la base de datos
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/reinas", "root", "");

                // Preparar la sentencia SQL para insertar los datos
                String sql = "INSERT INTO reinas (nombre, calificacion_inteligencia, calificacion_belleza, nombre_usuario) VALUES (?, ?, ?, ?)";
                PreparedStatement statement = connection.prepareStatement(sql);

                // Establecer los valores de los parámetros
                statement.setString(1, "Reina 2");
                statement.setInt(2, inteligencia2);
                statement.setInt(3, belleza2);
                statement.setString(4, CalificarReinaForm2.nombreUsuario);

                // Ejecutar la sentencia SQL
                statement.executeUpdate();

                // Cerrar la conexión y liberar recursos
                statement.close();
                connection.close();

                // Mostrar un mensaje de éxito al usuario
                JOptionPane.showMessageDialog(this, "Los datos se guardaron correctamente en la base de datos.");
            } catch (SQLException e) {
                // Mostrar un mensaje de error si ocurre algún problema con la base de datos
                JOptionPane.showMessageDialog(this, "Error al guardar los datos en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Mostrar mensaje de confirmación
            JOptionPane.showMessageDialog(this, "Los datos se han guardado exitosamente.", "Guardado exitoso", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            // Mostrar mensaje de error si los datos ingresados no son válidos
            JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos para la inteligencia y la belleza.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldInteligenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInteligenciaActionPerformed
        // TODO add your handling code here:
    // TODO add your handling code here:
    String inteligenciaText = jTextFieldInteligencia.getText();

    // Validar que el texto sea un número entre 0 y 10
    try {
        int inteligencia2 = Integer.parseInt(inteligenciaText);
        if (inteligencia2 < 0 || inteligencia2 > 10) {
            // Mostrar mensaje de error si el número está fuera del rango
            JOptionPane.showMessageDialog(this, "Ingrese un número entre 0 y 10 para la inteligencia.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            
        }
    } catch (NumberFormatException e) {
        // Mostrar mensaje de error si el texto no es un número válido
        JOptionPane.showMessageDialog(this, "Ingrese un número válido para la inteligencia.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jTextFieldInteligenciaActionPerformed

    private void jTextFieldBellezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBellezaActionPerformed
        // TODO add your handling code here:
    // TODO add your handling code here:
    // Obtener el texto ingresado en el campo de belleza
    String bellezaText = jTextFieldBelleza.getText();

    // Validar que el texto sea un número entre 0 y 10
    try {
        int belleza2 = Integer.parseInt(bellezaText);
        if (belleza2 < 0 || belleza2 > 10) {
            // Mostrar mensaje de error si el número está fuera del rango
            JOptionPane.showMessageDialog(this, "Ingrese un número entre 0 y 10 para la belleza.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            
        }
    } catch (NumberFormatException e) {
        // Mostrar mensaje de error si el texto no es un número válido
        JOptionPane.showMessageDialog(this, "Ingrese un número válido para la belleza.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jTextFieldBellezaActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
    // Cerrar la ventana actual
    dispose();

    // Crear una instancia de la ventana anterior (Menu)
    CalificarReinaForm menu = new CalificarReinaForm();

    // Pasar los datos guardados a la ventana de información
    menu.setDato2(Integer.toString(inteligencia2));
    menu.setDato3(Integer.toString(belleza2));

    // Hacer visible el JFrame
    menu.setVisible(true);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalificarReinaForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalificarReinaForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalificarReinaForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalificarReinaForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalificarReinaForm2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondos;
    private javax.swing.JLabel jLabelInteligencia;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldBelleza;
    private javax.swing.JTextField jTextFieldInteligencia;
    // End of variables declaration//GEN-END:variables


}