
package ventanas;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author User
 */
public class Interfaz extends javax.swing.JFrame {
    
    public static String nombreUsuarioGlobal = "";

    SQLConectar conSQL = new SQLConectar();
    String nombreUsuario = ""; 
    
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelIcono = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jTextFieldUser = new javax.swing.JTextField();
        jButtonSesion = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 102, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/R.png"))); // NOI18N
        jLabelIcono.setText("jLabel1");
        getContentPane().add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 90, 480, 520));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 700, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, -1, -1));

        jPassword.setBackground(new java.awt.Color(102, 102, 0));
        jPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 700, 210, -1));

        jTextFieldUser.setBackground(new java.awt.Color(102, 102, 0));
        jTextFieldUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 210, -1));

        jButtonSesion.setBackground(new java.awt.Color(102, 102, 0));
        jButtonSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSesion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSesion.setText("Iniciar Seción");
        jButtonSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 770, -1, -1));

        jLabelFondo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/R11.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-450, -10, 960, 1086));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserActionPerformed
        // TODO add your handling code here:
    String usuario = jTextFieldUser.getText(); // Obtener el texto ingresado en el jTextFieldUser
    
    // Aquí puedes agregar la lógica que deseas realizar con el usuario ingresado
    // Por ejemplo, puedes mostrar un mensaje con el usuario ingresado
    
    JOptionPane.showMessageDialog(this, "Usuario ingresado: " + usuario);
    
    // También puedes utilizar la variable nombreUsuario aquí
    JOptionPane.showMessageDialog(this, "Nombre de usuario guardado: " + nombreUsuario);
    }//GEN-LAST:event_jTextFieldUserActionPerformed

    private void jButtonSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSesionActionPerformed
        // TODO add your handling code here:
    String usuario = jTextFieldUser.getText();
    String contraseña = new String(jPassword.getPassword());

        try {
            Connection con = conSQL.getConectarDB();

            String consulta = "SELECT * FROM usuarios WHERE nombre_usuario = ? AND contrasena = ?";
            PreparedStatement pst = con.prepareStatement(consulta);
            pst.setString(1, usuario);
            pst.setString(2, contraseña);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                int nivelAcceso = rs.getInt("nivel_acceso");

                nombreUsuario = rs.getString("nombre_usuario"); // Obtener el nombre de usuario

                if (nivelAcceso == 1) {
                    JOptionPane.showMessageDialog(this, "¡Bienvenido, usuario nivel 1!");

                    String consultaGuardarUsuario = "UPDATE usuarios SET nombre_usuario = ? WHERE nombre_usuario = ?";
                    PreparedStatement pstGuardarUsuario = con.prepareStatement(consultaGuardarUsuario);
                    pstGuardarUsuario.setString(1, nombreUsuario);
                    pstGuardarUsuario.setString(2, nombreUsuario);

                    pstGuardarUsuario.executeUpdate();
                    pstGuardarUsuario.close();

                    MenuNivel1 menuNivel1 = new MenuNivel1();
                    menuNivel1.setNombreUsuario(nombreUsuario);
    
                    menuNivel1.setVisible(true);
                    this.dispose();
                } else if (nivelAcceso == 2) {
                    JOptionPane.showMessageDialog(this, "¡Bienvenido, usuario nivel 2!");

                    String consultaGuardarUsuario = "UPDATE usuarios SET nombre_usuario = ? WHERE nombre_usuario = ?";
                    PreparedStatement pstGuardarUsuario = con.prepareStatement(consultaGuardarUsuario);
                    pstGuardarUsuario.setString(1, nombreUsuario);
                    pstGuardarUsuario.setString(2, nombreUsuario);

                    pstGuardarUsuario.executeUpdate();
                    pstGuardarUsuario.close();

                    MenuNivel2 menuNivel2 = new MenuNivel2();
                    menuNivel2.setNombreUsuario(nombreUsuario);
                    Interfaz.nombreUsuarioGlobal = nombreUsuario; // Establecer el valor en la variable estática
                    menuNivel2.setVisible(true);
                    CalificarReinaForm1 calificarReinaForm1 = new CalificarReinaForm1();
                    calificarReinaForm1.setNombreUsuario(nombreUsuario);
                    CalificarReinaForm2 calificarReinaForm2 = new CalificarReinaForm2();
                    calificarReinaForm2.setNombreUsuario(nombreUsuario);
                    CalificarReinaForm3 calificarReinaForm3 = new CalificarReinaForm3();
                    calificarReinaForm3.setNombreUsuario(nombreUsuario);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Credenciales inválidas");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Credenciales inválidas");
            }

            rs.close();
            pst.close();
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSesionActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    char[] password = jPassword.getPassword(); // Obtener la contraseña ingresada como un arreglo de caracteres
    
    // Aquí puedes agregar la lógica que deseas realizar con la contraseña ingresada
    // Por ejemplo, puedes convertir el arreglo de caracteres en una cadena y mostrarla en la consola
    
    String contraseña = new String(password);
    System.out.println("Contraseña ingresada: " + contraseña);
    }//GEN-LAST:event_jPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
