/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reinas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class CALIFICAR extends javax.swing.JFrame {
    Conexion conexion = new Conexion("calificaciones");
    Connection cn = conexion.conectar();
    public CALIFICAR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bellezaR1 = new javax.swing.JTextField();
        bellezaR2 = new javax.swing.JTextField();
        bellezaR3 = new javax.swing.JTextField();
        inteligenciaR1 = new javax.swing.JTextField();
        inteligenciaR2 = new javax.swing.JTextField();
        inteligenciaR3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbtGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("CALIFIQUE A LAS REINAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("LAS CALIFICACIONES SON DE 1-10");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel4.setText("BELLEZA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel5.setText("INTELIGENCIA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        bellezaR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bellezaR1ActionPerformed(evt);
            }
        });
        jPanel1.add(bellezaR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 70, 40));
        jPanel1.add(bellezaR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 70, 40));
        jPanel1.add(bellezaR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 70, 40));

        inteligenciaR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inteligenciaR1ActionPerformed(evt);
            }
        });
        jPanel1.add(inteligenciaR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 70, 40));

        inteligenciaR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inteligenciaR2ActionPerformed(evt);
            }
        });
        jPanel1.add(inteligenciaR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 70, 40));
        jPanel1.add(inteligenciaR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 70, 40));

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 120, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("REINA 1");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("REINA 2");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("REINA 3");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jbtGuardar.setText("GUARDAR");
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURES/FONDO2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void inteligenciaR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inteligenciaR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inteligenciaR1ActionPerformed

    private void inteligenciaR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inteligenciaR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inteligenciaR2ActionPerformed

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed

       PreparedStatement calificaciones;
        try {
            calificaciones = cn.prepareStatement("INSERT INTO reinas(REINAS,BELLEZA,INTELIGENCIA) VALUES(?,?,?)");
            calificaciones.setString(1,"Reina 1");
            calificaciones.setString(2,bellezaR1.getText());
            calificaciones.setString(3,inteligenciaR1.getText());
            calificaciones.executeUpdate();
            calificaciones = cn.prepareStatement("INSERT INTO reinas(REINAS,BELLEZA,INTELIGENCIA) VALUES(?,?,?)");
            calificaciones.setString(1,"Reina 2");
            calificaciones.setString(2,bellezaR2.getText());
            calificaciones.setString(3,inteligenciaR2.getText());
            calificaciones.executeUpdate();
            calificaciones = cn.prepareStatement("INSERT INTO reinas(REINAS,BELLEZA,INTELIGENCIA) VALUES(?,?,?)");
            calificaciones.setString(1,"Reina 3");
            calificaciones.setString(2,bellezaR3.getText());
            calificaciones.setString(3,inteligenciaR3.getText());
            calificaciones.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(CALIFICAR.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Se guardo las calificaciones correctamente");
    }//GEN-LAST:event_jbtGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login inicio = new Login();
        inicio.setVisible(true);
        inicio.setLocationRelativeTo(null);
        this.dispose();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bellezaR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bellezaR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bellezaR1ActionPerformed
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CALIFICAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CALIFICAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CALIFICAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CALIFICAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CALIFICAR().setVisible(true);
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bellezaR1;
    private javax.swing.JTextField bellezaR2;
    private javax.swing.JTextField bellezaR3;
    private javax.swing.JTextField inteligenciaR1;
    private javax.swing.JTextField inteligenciaR2;
    private javax.swing.JTextField inteligenciaR3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtGuardar;
    // End of variables declaration//GEN-END:variables
}
