
package zoologico;

/**
 *
 * @author HP
 */
public class ZOO extends javax.swing.JFrame {
    public ZOO() {
        initComponents();
    }
    public void info (String id){
        mostrar info = new mostrar(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PANDA = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        COCODRILO = new javax.swing.JButton();
        TUCAN = new javax.swing.JButton();
        RINOCERONTE = new javax.swing.JButton();
        MONO = new javax.swing.JButton();
        GAZELLA = new javax.swing.JButton();
        ZORRO = new javax.swing.JButton();
        LEON = new javax.swing.JButton();
        imgprincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PANDA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PANDA.setText("P----_");
        PANDA.setToolTipText("Panda");
        PANDA.setContentAreaFilled(false);
        PANDA.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        PANDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PANDAActionPerformed(evt);
            }
        });
        jPanel1.add(PANDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 73, 160, 180));

        jLabel4.setToolTipText("PANDA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 150, 160));

        COCODRILO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        COCODRILO.setText("C----_");
        COCODRILO.setToolTipText("Cocodrilo");
        COCODRILO.setContentAreaFilled(false);
        COCODRILO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        COCODRILO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COCODRILOActionPerformed(evt);
            }
        });
        jPanel1.add(COCODRILO, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 23, 200, 150));

        TUCAN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TUCAN.setText("T----_");
        TUCAN.setToolTipText("Tucan");
        TUCAN.setContentAreaFilled(false);
        TUCAN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        TUCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUCANActionPerformed(evt);
            }
        });
        jPanel1.add(TUCAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 180, 180));

        RINOCERONTE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RINOCERONTE.setText("R-----_");
        RINOCERONTE.setToolTipText("Rinoceronte");
        RINOCERONTE.setContentAreaFilled(false);
        RINOCERONTE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        RINOCERONTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RINOCERONTEActionPerformed(evt);
            }
        });
        jPanel1.add(RINOCERONTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 180, 160));

        MONO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MONO.setText("M---_");
        MONO.setToolTipText("Mono");
        MONO.setContentAreaFilled(false);
        MONO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MONO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MONOActionPerformed(evt);
            }
        });
        jPanel1.add(MONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 190, 160));
        MONO.getAccessibleContext().setAccessibleName("M----_");

        GAZELLA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        GAZELLA.setText("G----_");
        GAZELLA.setToolTipText("Gacela");
        GAZELLA.setContentAreaFilled(false);
        GAZELLA.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        GAZELLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GAZELLAActionPerformed(evt);
            }
        });
        jPanel1.add(GAZELLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 393, 180, 180));

        ZORRO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ZORRO.setText("Z-----_");
        ZORRO.setToolTipText("Zorro");
        ZORRO.setContentAreaFilled(false);
        ZORRO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ZORRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZORROActionPerformed(evt);
            }
        });
        jPanel1.add(ZORRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 443, 170, 150));

        LEON.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LEON.setText("L----_");
        LEON.setToolTipText("Leon");
        LEON.setContentAreaFilled(false);
        LEON.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LEON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LEONActionPerformed(evt);
            }
        });
        jPanel1.add(LEON, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 263, 170, 170));

        imgprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURS/ZOOLOGICO.png"))); // NOI18N
        imgprincipal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                imgprincipalAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(imgprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TUCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUCANActionPerformed
        mostrar opciones = new mostrar("5");
        opciones.setVisible(true);
        opciones.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_TUCANActionPerformed

    private void imgprincipalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_imgprincipalAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_imgprincipalAncestorAdded

    private void LEONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LEONActionPerformed
        mostrar opciones = new mostrar("2");
        opciones.setVisible(true);
        opciones.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_LEONActionPerformed

    private void GAZELLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GAZELLAActionPerformed
        mostrar opciones = new mostrar("8");
        opciones.setVisible(true);
        opciones.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_GAZELLAActionPerformed

    private void COCODRILOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COCODRILOActionPerformed
        mostrar opciones = new mostrar("1");
        opciones.setVisible(true);
        opciones.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_COCODRILOActionPerformed

    private void ZORROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZORROActionPerformed
         mostrar opciones = new mostrar("3");
        opciones.setVisible(true);
        opciones.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_ZORROActionPerformed

    private void RINOCERONTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RINOCERONTEActionPerformed
         mostrar opciones = new mostrar("4");
        opciones.setVisible(true);
        opciones.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_RINOCERONTEActionPerformed

    private void PANDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PANDAActionPerformed
         mostrar opciones = new mostrar("6");
        opciones.setVisible(true);
        opciones.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_PANDAActionPerformed

    private void MONOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MONOActionPerformed
         mostrar opciones = new mostrar("7");
        opciones.setVisible(true);
        opciones.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_MONOActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton COCODRILO;
    private javax.swing.JButton GAZELLA;
    private javax.swing.JButton LEON;
    private javax.swing.JButton MONO;
    private javax.swing.JButton PANDA;
    private javax.swing.JButton RINOCERONTE;
    private javax.swing.JButton TUCAN;
    private javax.swing.JButton ZORRO;
    private javax.swing.JLabel imgprincipal;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
